apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mlops-inference-service.fullname" . }}
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: mlops-inference-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
