apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: django-app
  endpoints:
    - port: {{ .Values.service.port }}
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - default 
