global:
  image:
    tag: v2.10.4

configs:
  cm:
    timeout.reconciliation: 30s
    accounts.devops: apiKey,login

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, devops, role:admin

server:
  replicas: 1
  extraArgs:
    - --insecure
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

controller:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

applicationSet:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

redis:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

crds:
  install: true
