FROM python:3.9-slim as builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 libsm6 libxrender1 libxext6 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir --target=/python-deps -r requirements.txt

FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /python-deps /usr/local/lib/python3.9/site-packages/

COPY example.jpg .
COPY inference.py .
COPY model.pt .

ENTRYPOINT ["python", "inference.py", "example.jpg"]
