apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: infra-tools # ArgoCD namespace
spec:
  project: default

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 20.0.1
      helm:
        valueFiles:
          - $values/namespaces/application/nginx-values.yaml

    - repoURL: https://github.com/Matajur/MLOps.git
      targetRevision: lesson-7
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: application

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
